import { NextRequest } from 'next/server'
import { sql } from 'drizzle-orm'
import { db } from '@/lib/db'
import { requirePermission, requireSession } from '@/lib/api/auth'
import { fail, ok } from '@/lib/api/http'

type Ctx={params:Promise<{id:string}>}
export async function GET(_:NextRequest,{params}:Ctx){try{await requireSession()}catch(e){if(e instanceof Error&&e.message==='UNAUTHORIZED')return fail('Autenticação necessária.',401);return fail('Não foi possível autorizar.',403)}const {id}=await params;const rows=await db.execute(sql`SELECT t.*, c.name AS category_name, u.name AS author_name FROM forum_threads t JOIN forum_categories c ON c.id=t.category_id JOIN "user" u ON u.id=t.author_id WHERE t.id=${id} AND t.status <> 'ARCHIVED'`);if(!rows.length)return fail('Thread não encontrada.',404);return ok({thread:rows[0]})}
export async function PATCH(request:NextRequest,{params}:Ctx){try{const s=await requireSession();const {id}=await params;const b=await request.json();const own=await db.execute(sql`SELECT author_id FROM forum_threads WHERE id=${id}`);if(!own.length)return fail('Thread não encontrada.',404);if(own[0].author_id!==s.user.id){try{await requirePermission('forum.moderate')}catch{return fail('Sem autorização.',403)}}if(b.status&&!['OPEN','LOCKED','SOLVED','ARCHIVED'].includes(b.status))return fail('Status inválido.',422);const r=await db.execute(sql`UPDATE forum_threads SET title=COALESCE(${b.title??null},title), body=COALESCE(${b.body??null},body), status=COALESCE(${b.status??null},status), updated_at=NOW() WHERE id=${id} RETURNING *`);await db.execute(sql`INSERT INTO audit_logs (actor_id, action, entity_type, entity_id) VALUES (${s.user.id}, 'FORUM_POST_UPDATED', 'forum_thread', ${id})`);return ok({thread:r[0]})}catch(e){if(e instanceof Error&&e.message==='UNAUTHORIZED')return fail('Autenticação necessária.',401);return fail('Não foi possível atualizar.',409)}}
export async function DELETE(_:NextRequest,{params}:Ctx){try{const s=await requireSession();const {id}=await params;const own=await db.execute(sql`SELECT author_id FROM forum_threads WHERE id=${id}`);if(!own.length)return fail('Thread não encontrada.',404);if(own[0].author_id!==s.user.id){try{await requirePermission('forum.moderate')}catch{return fail('Sem autorização.',403)}}await db.execute(sql`UPDATE forum_threads SET status='ARCHIVED',updated_at=NOW() WHERE id=${id}`);await db.execute(sql`INSERT INTO audit_logs (actor_id, action, entity_type, entity_id) VALUES (${s.user.id}, 'FORUM_POST_DELETED', 'forum_thread', ${id})`);return ok({deleted:true})}catch(e){if(e instanceof Error&&e.message==='UNAUTHORIZED')return fail('Autenticação necessária.',401);return fail('Não foi possível excluir.',409)}}
